LOGIN_CREDENCIALES_INVALIDAS = 'Lo sentimos, no pudimos encontrar tu cuenta o la contraseña es invalida.'
LOGOUT_EXITOSO = 'Cerraste sesión exitosamente.'
LOGIN_EXITOSO = 'Bienvenido(a) a SkyCast'
SUCCESS = 'success'
WARNING = 'warning'
ERROR = 'error'
